### PR TITLE
chore: 🤖 add support for fast-forward github action

### PR DESCRIPTION
**Pull request by prashantasdeveloper**
### Description

This adds support for fast forwarding with PR comments

### Breaking Changes

NA

### JIRA Link

DA-1215

### Checklist

- [ ] Updated the Readme.md (if required) ?

### CODE REVIEW

**Review by polymath-eric — COMMENTED** [review]
shouldn't this go into alpha?

I guess its OK now since both are synced atm, but if this gets merged into master, then another alpha PR merge could mess up the linear history requirement.

I know we don't have it enabled on this repo so maybe its OK?

**Comment by prashantasdeveloper** [comment]
> shouldn't this go into alpha?
> 
> I guess its OK now since both are synced atm, but if this gets merged into master, then another alpha PR merge could mess up the linear history requirement.
> 
> I know we don't have it enabled on this repo so maybe its OK?

For actions to work in alpha, the action should be present in master first. Then only the workflow gets triggered in other branches.

**Review by VictorVicente — APPROVED** [review]

**Pull request merged**
