### PR TITLE
fix: 🐛 Fix transfer with memo

### PR DESCRIPTION
**Pull request by polymath-eric**
### Description

Fix transfer with memo

### Breaking Changes

N/A

### Checklist

- [ ] Updated the Readme.md (if required) ?

### CODE REVIEW

**Comment by prashantasdeveloper** [comment]
Seems like this got left out with upgrade. My only concern here is if we are switching the `padString` with `padEnd` shouldn't we just do that in `conversion` util func? That should take care of any other possibility even if that gets overlooked by us

**Review by VictorVicente — APPROVED** [review]

**Comment by polymath-eric** [comment]
@prashantasdeveloper What do you mean by:

> Seems like this got left out with upgrade. My only concern here is if we are switching the padString with padEnd shouldn't we just do that in conversion util func? That should take care of any other possibility even if that gets overlooked by us

The changes are in conversion, and the test file for conversion only

**Comment by prashantasdeveloper** [comment]
My bad. I meant directly updating the `padString` function present in `internal.ts`. Are we sure other instances where `padString` is used aren't affected?

**Review by prashantasdeveloper — APPROVED** [review]

**Comment by polymath-eric** [comment]
Made a ticket for Prashant's suggetion. For now I want to focus on webhooks rather then test all the callers of that method.

https://polymath.atlassian.net/browse/DA-403

**Comment by F-OBrien** [comment]
> My bad. I meant directly updating the `padString` function present in `internal.ts`. Are we sure other instances where `padString` is used aren't affected? Maybe pick that up later and create a JIRA ticket instead.

Did we establish if the `padString` with null characters or the `Memo` createType was the root cause? `padString` is used in multiple other places. Primarily on tickers so editing it potentially has wider implications than just addressing memos.

As an aside, I prefer the way querying strings padded with spaces are reported in plain text instead of hex encoded strings when viewing events in Subscan and using the polkadot.js app interface. So if there is no reason to keep padding with null characters it might be worth considering spaces as the default padding.

**Pull request merged**
