### PR TITLE
test: 💍 add nft creation with name test case

### PR DESCRIPTION
**Pull request by polymath-eric**
### Description

add nft missing coverage case

### Checklist

- [ ] Updated the Readme.md (if required) ?

### CODE REVIEW

**Review by prashantasdeveloper — APPROVED** [review]

**Comment by polymath-eric** [comment]
I don't get why a merge into alpha would be OK without this case, but the alpha into beta is missing the coverage. The double ?? is bad for sonar complexity measure though, it wants 8 cases


sonar-complexity

**Pull request merged**
