### PR TITLE
feat: 🎸 bump supported chain version to 5.0.2

### PR DESCRIPTION
**Pull request by polymath-eric**
### Description

Bump version check to 5.0.2

### Breaking Changes

N/A

### JIRA Link

[DA-395](https://polymath.atlassian.net/browse/DA-395)

### Checklist

- [ ] Updated the Readme.md (if required) ?

### CODE REVIEW

**Review by monitz87 — COMMENTED** [review]
Are we sure both versions got updated to 5.0.2?

**Comment by polymath-eric** [comment]
There is a function in there that adds the dots to the spec version. Both are updated on staging like this, which is what is being promoted to release.

@monitz87 

https://staging-app.polymesh.live/#/explorer

**Review by VictorVicente — APPROVED** [review]

**Comment by VictorVicente** [comment]
I've rebased the PR to `beta` and approved.

**Pull request merged**
