### PR TITLE
Alpha into beta

### PR DESCRIPTION
**Pull request by polymath-eric**
### Description

Bring alpha into beta. This removes TransactionQueues

### Checklist

- [ ] Updated the Readme.md (if required) ?

### CODE REVIEW

**Review by prashantasdeveloper — APPROVED** [review]

**Review by prashantasdeveloper — APPROVED** [review]

**Comment by polymath-eric** [comment]
There are 5 smells, but I think they are all OK to ignore. 3 from deprecated code, 2 from a type assertion it seems like we do need

**Pull request merged**
