### PR TITLE
docs: ✏️ Escape `@` in README to correctly render Github pages

### PR DESCRIPTION
**Pull request by prashantasdeveloper**
### Description

Fix ReadME to allow proper rendering of github pages

### Breaking Changes

NA

### JIRA Link

NA

### Checklist

- [ ] Updated the Readme.md (if required) ?

### CODE REVIEW

**Review by polymath-eric — DISMISSED** [review]

**Comment by polymath-eric** [comment]
Maybe we can put this into alpha? The branches are all up to date and we are going to be releasing soonish I think.

This is docs only, and been like this for awhile. Seems like a small change to clutter up the git history imo

**Review by VictorVicente — APPROVED** [review]

**Pull request merged**
