### PR TITLE
Merge pull request #855 from PolymeshAssociation/beta

### PR DESCRIPTION
**Pull request by polymath-eric**
### Description

Update beta with master

### Checklist

- [ ] Updated the Readme.md (if required) ?

### CODE REVIEW

**Comment by polymath-eric** [comment]
this seems a bit redundant to me, but it seems better to ensure beta contains every commit of master just in case

**Comment by polymath-eric** [comment]
Lots of code smells I think we ignored previously

**Review by prashantasdeveloper — APPROVED** [review]

**Pull request merged**
