### PR TITLE
feat: 🎸 remove updated_at in queries

### PR DESCRIPTION
**Pull request by polymath-eric**
### Description

remove querying for `updated_at` field from SubQuery

### Breaking Changes

None

### JIRA Link

N/A

### Checklist

- [ ] Updated the Readme.md (if required) ?

### CODE REVIEW

**Comment by polymath-eric** [comment]
I added the field into SQ for now, but this will set us up to be able to remove it in the future

**Review by VictorVicente — APPROVED** [review]

**Review by prashantasdeveloper — APPROVED** [review]

**Pull request merged**
