### PR TITLE
feat: 🎸 Update dependencies

### PR DESCRIPTION
**Pull request by prashantasdeveloper**
### Description

Update dependencies to their latest compatible versions

### Breaking Changes

NA

### JIRA Link

DA-851

### Checklist

- [ ] Updated the Readme.md (if required) ?

### CODE REVIEW

**Review by VictorVicente — APPROVED** [review]

**Comment by VictorVicente** [comment]
@prashantasdeveloper could you check why Sonar says coverage is not enough? Maybe a test in `conversion` must be added.

**Comment by prashantasdeveloper** [comment]
I have added the missing line coverage but it seems the others are for V5 dual lines coverage

**Pull request merged**
