### PR TITLE
ci: 🎡 Add support for fast-forward merges

### PR DESCRIPTION
**Pull request by prashantasdeveloper**
### Description

Add support for fast-forward merges using https://github.com/marketplace/actions/fast-forward-merge

### Breaking Changes

NA

### JIRA Link

DA-1161

### Checklist

- [ ] Updated the Readme.md (if required) ?

### CODE REVIEW

**Review by polymath-eric — APPROVED** [review]

**Comment by polymath-eric** [comment]
lgtm. maybe it needs to be merged into alpha before /fast-forward works?

**Comment by VictorVicente** [comment]
Why `CI / Building and releasing project (pull_request)` has been skipped?

**Comment by prashantasdeveloper** [comment]
> Why `CI / Building and releasing project (pull_request)` has been skipped?

I didn't thing the pull request needed releasing check. Only on push we need that check @VictorVicente

**Comment by prashantasdeveloper** [comment]
> lgtm. maybe it needs to be merged into alpha before /fast-forward works?

You are right @polymath-eric . Once this is merged in alpha, we  can then only take advantage of commenting `/fast-forward`

**Pull request merged**
