### PR TITLE
feat: 🎸 Drop support for chain 6.x

### PR DESCRIPTION
**Pull request by prashantasdeveloper**
### Description

Remove legacy v6 code and drop support for 6.x chain.

### BREAKING CHANGE: 🧨

SDK no longer supports chain 6.x
- Drops support for `6.3` spec version
- type of `signers` has been changed to `Account` type in `MultiSigDetails` and `MultiSigSigners`.
This affects `details` method in `MultiSig` entity and `getMultiSigSigners` in `Identity` entity
- Deprecated `getSubsidy` method of the `Account` entity has been removed.
- Deprecated `ticker` field has been removed from the interface `MetadataKeyId`. This affects
`getCollectionKeys` method from `NftCollection` entity
- Deprecated `ticker` field has been removed from `HumanReadable` interfaces for these entities:
`Checkpoint`, `CheckpointSchedule`, `CorporateAction`, `DividendDistribution`,
`CustomPermissionGroup`, `KnownPermissionGroup`, `MetadataEntry`, `Offering`,
- Deprecated `ticker` field has been dropped from method arguments of `getTransactionHistory` of
`Portfolios` namespace and `Portfolio` entity
- `Ticker` value has been removed from `ScopeType` enum
- `ticker` field has been renamed to `assetId` in `ClaimScope` interface
- Deprecated `did` and `ticker` fields of the `BaseAsset` entity have been removed.
- Deprecated `joinCreator` method of `MultiSig` entity has been removed

### JIRA Link

DA-1307

### Checklist

- [ ] Updated the Readme.md (if required) ?

### CODE REVIEW

**Comment by prashantasdeveloper** [comment]
Triggered from https://github.com/PolymeshAssociation/polymesh-sdk/pull/1304#issuecomment-2508050359 by [@&ZeroWidthSpace;polymath-eric](https://github.com/polymath-eric).

Trying to  fast forward `alpha` (5ce3a3809bea50a0321e72c5a67cda6a17f88983) to `remove-legacy-code` (a923766bb89d77759fca5dca243a29e90d0c1fad).

Target branch (`alpha`):

```shell
commit 5ce3a3809bea50a0321e72c5a67cda6a17f88983 (HEAD -> alpha, tag: v27.0.0-alpha.10, origin/alpha)
Author: Eric Richardson <eric@polymesh.network>
Date:   Thu Nov 21 12:27:50 2024 -0500

    feat: 🎸 add support for padded IDs in subquery
    
    Add dual version SubQuery support. v19+ SQ instance will pad block ID
    values so ordering by created block is such that the lexical order is
    equivalent to numerical order. Also created_at column has been removed
    as the padding makes it redundant (it was the time of sync, not the time
    on chain).
```

Pull request (`remove-legacy-code`):

```shell
commit a923766bb89d77759fca5dca243a29e90d0c1fad (pull_request/remove-legacy-code)
Author: Prashant Bajpai <34747455+prashantasdeveloper@users.noreply.github.com>
Date:   Thu Nov 21 19:29:02 2024 +0530

    feat: 🎸 Add more info about historical proposal
    
    BREAKING CHANGE: 🧨 Return type of `MultiSig.getHistoricalProposals` is now changed to
    `ResultSet<HistoricalMultiSigProposal>` to provide more info about the
    proposal. This will allow get know information about prunded proposals
    as well
```
Fast forwarding `alpha` (5ce3a3809bea50a0321e72c5a67cda6a17f88983) to `remove-legacy-code` (a923766bb89d77759fca5dca243a29e90d0c1fad).
```shell
$ git push origin a923766bb89d77759fca5dca243a29e90d0c1fad:alpha
remote: error: GH006: Protected branch update failed for refs/heads/alpha.        
remote: 
remote: - Waiting on code owner review from PolymeshAssociation/middleware.        
To https://github.com/PolymeshAssociation/polymesh-sdk.git
 ! [remote rejected]   a923766bb89d77759fca5dca243a29e90d0c1fad -> alpha (protected branch hook declined)
error: failed to push some refs to 'https://github.com/PolymeshAssociation/polymesh-sdk.git'

**Review by polymath-eric — APPROVED** [review]

**Review by polymath-eric — APPROVED** [review]

**Pull request merged**
